[project]
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["conda-forge"]
name = "editable-with-extras"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[dependencies]
python = "3.12"

[pypi-dependencies]
package_with_config_settings = { path = "./package_with_extras", editable = true, config_settings = "editable_mode=compat" }
